name: Manual Trigger Workflow

on:
  workflow_dispatch: # Enables manual trigger from the GitHub GUI or API.

jobs:
  trigger-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run a simple command
      run: echo "Workflow triggered manually!"
